### PR TITLE
Allow untrimmed whitespace according to YAML.

### PR DESCRIPTION
**Pull request by dmitchellmim**
*	Allow spaces when explicitly quoted (e.g. `" spaced "`).
*	Abide by [YAML's chomping rules with multi-line strings](https://yaml.org/spec/1.2/spec.html#id2794534).
	*	`|` preserves only the final line break ("clip").
	*	`|-` strips all trailing line breaks ("strip").
	*	`|+` preserves all trailing line breaks ("keep").

When using Play's default i18n, [it's possible to have strings with leading and trailing spaces](https://stackoverflow.com/questions/18451405/play-framework-2-i18n-use-of-space-in-conf-file), but I discovered that this plugin was trimming those spaces. This change adds that functionality, including for multi-line strings (breaking change for anyone using `|`).

### CODE REVIEW

**Comment by KarelCemus** [comment]
Hi @dmitchellmim, thanks for your contribution! I'll fix build this week and merge this. It looks good.

**Comment by KarelCemus** [comment]
could you please rebase your branch onto master? I fixed travis and added support of scala 2.13

**Comment by dmitchellmim** [comment]
Did I do it correctly? I'm used to rebasing in Mercurial but not in Git.

**Comment by KarelCemus** [comment]
Not exactly, you merged branches, not rebased your branch. The code base is same in the end but commit history is different and more tangled this way. Could you give me a write permission into your branch so I could fix it?

**Comment by KarelCemus** [comment]
Never mind, I merged it directly outside this PR, therefore I am closing this. Thanks for your contribution

**Comment by KarelCemus** [comment]
Released

**Pull request closed without merging**
