### PR TITLE
Separate message loading / format support from MessagesApi

### PR DESCRIPTION
**Pull request by egao1980**
This PR would allow to reuse multi format file loading with custom implementations of MessagesApi (i.e. ICU) without the need to pull in any extra dependencies into this project. 

Minor updates:
- Play version bumped to 2.8.8
- JSON loading added as a low hanging fruit as YAML 1.2 is a superset of JSON.

### CODE REVIEW

**Comment by KarelCemus** [comment]
Hey, very nice PR, thank you for your contribution. I slightly polished the code and pushed the changes into https://github.com/KarelCemus/play-i18n/tree/gemini-separate-loaders-module branch in this repo since I don't have write access to the original branch. 

I am willing to merge it I have a just one question which puzzles me. 

```
      Format("json", Some("json"), YamlFileLoader)
```

Why do you use Yaml loader for JSON files? I'd expect it should work. Why don't we use a specific loader for a specific file type? Yaml loader parses the file as yaml, which json is not

**Comment by egao1980** [comment]
Thanks for the swift review. 

On JSON - according to YAML spec, YAML 1.2+ has to be compatible with JSON so JSON document is a valid YAML 1.2+ document. Hence we can support JSON file loading without a separate file format handler. And it works as proven by tests. Without additional dependencies.

**Comment by KarelCemus** [comment]
I see, nice. I'll merge it later today, thank you

**Comment by KarelCemus** [comment]
Manually merged

**Comment by KarelCemus** [comment]
Released 2.2.0

**Pull request closed without merging**
